### ISSUE TITLE
运行出错，没有找到模板文件

### ISSUE THREAD

**Issue by zhnaglei** [cong5/myPersimmon#10]
你好，如果可以，可以将你的源码给我发一份吗？我按照安装步骤，一步一步执行，到最后出现前台出现laravel的欢迎页面，后台报模板找不到的错。

**Comment by cong5** [comment]
仓库里面就是完整的源码啊。版本跟我的博客一样的。你先`git clone https://github.com/cong5/myPersimmon.git` 然后再在clone下来的项目目录里面执行安装步骤。
