### ISSUE TITLE
路由相关

### ISSUE THREAD

**Issue by 3tuuu** [cong5/myPersimmon#14]
您好, 我想请问下为何我用vue.js做的单页面刷新后,变成404了. 我参照了vue-router的apache配置,但是当我修改以后,会报错.于是我又在项目中加入了.htaccess,仍然不行.可我能在本地环境运行你的项目QWQ....初次接触,很多都不会,还望见谅...

**Comment by cong5** [comment]
你本地使用是什么环境？amp？还是nmp？
把你伪静态规则贴出来我看看。
