### ISSUE TITLE
数据库迁移

### ISSUE THREAD

**Issue by Chain-Zhang** [cong5/myPersimmon#15]
![image](https://user-images.githubusercontent.com/14361273/28255975-1c154dba-6af0-11e7-8493-64c1a5d55702.png)
我在执行`php artisan migrate`的时候报上图中的错，是怎么回事啊

**Comment by cong5** [comment]
你电脑上使用的是什么运行环境？是自己brew安装的还是使用的一些套件？manp pro、xampp之类的？

**Comment by cong5** [comment]
如果是mnmp pro 的，那么mysql的连接方式使用unix_socket `'unix_socket' => '/Applications/MAMP/tmp/mysql/mysql.sock',`

**Comment by maokeyang** [comment]
兄弟 你是不是没去建数据库

**Comment by cong5** [comment]
兄弟，数据库是需要你自己去建的，我没使用`homestead`之类的虚拟机可以自动创建数据库。

**Comment by Chain-Zhang** [comment]
```
'unix_socket' => '/Applications/MAMP/tmp/mysql/mysql.sock',
```
这样搞定了
