### ISSUE TITLE
后台的模板路径怎么走

### ISSUE THREAD

**Issue by zclgni** [cong5/myPersimmon#17]
xxxx.com/myp#/posts/add   他的模板地址是在哪儿呢，我把文件都翻遍了也没有找到具体的这个文件

**Comment by cong5** [comment]
后台管理的模板在这个路径：`resources/assets/backend/js/components/pager`
/posts/add 的模板文件在：`resources/assets/backend/js/components/pager/posts/post.vue`

模板文件全部是.vue文件
