### ISSUE TITLE
你的包在 linux 下使用 npm install 导致错误

### ISSUE THREAD

**Issue by rexleimo** [cong5/myPersimmon#19]
使用npm install 没有问题，使用 cnpm install 的话 cross-env 运行会报错
yarn install 写也是
一运行 npm run dev 就有问题了
npm ERR! Error: EPERM: operation not permitted, rename 'D:\vmroot\www\boke\node_modules\cross-env' -> 'D:\vmroot\www\boke\node_modules\.cross-env.DELETE'
npm ERR!     at moveAway (D:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (D:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)

但是在windows下缺没有问题

**Comment by cong5** [comment]
根据关键词，你先试试检查是不是目录或者文件权限的问题 `npm ERR! Error: EPERM: operation not permitted ` 操作不被允许。

**Comment by rexleimo** [comment]
原来在laravel 5.5 要 cross-env 全局 
不过 在Linux 上  无法使用  npm run dev 使用ubuntu 16.04 开发环境

**Comment by xiao6zi** [comment]
@rainbowMorelhahahah 以下或许能帮到你：
npm run dev 失败原因：[http://pilishen.com/posts/reason-and-solution-why-npm-run-dev-cannot-find-cross-env-in-laravel5.4](http://pilishen.com/posts/reason-and-solution-why-npm-run-dev-cannot-find-cross-env-in-laravel5.4)

解决方法：

1. npm install --no-bin-links
2. npm rebuild node-sass --no-bin-links
（Linux下这一步会报错，提示找不到 cross-env，这个时候修改项目根目录下的 package.json 文件，删除所有 scripts 下的 cross-env即可，然后重新执行命令。）
3. npm run dev

Ps： resources/assets/sass/app.scss 下的代码一定要填写准确！！
