### ISSUE TITLE
后台头像问题

### ISSUE THREAD

**Issue by xiao6zi** [cong5/myPersimmon#20]
![image](https://user-images.githubusercontent.com/26701271/32540298-3f9f6052-c4a7-11e7-9da4-e4675b975806.png)

\app\Http\Controllers\Backend\AuthController.php   66 行

$date 得到的结果 应该和 预期的不一样

还有个问题：  为啥 要设置 30 天 更新一次？这样 别人想设置个性头像不就每30天设置一次?

**Comment by cong5** [comment]
一般后台的头像都是自己看的。所以设置了一个比较长的过期时间。
