### ISSUE TITLE
The only supported ciphers are AES-128-CBC and AES-256-CBC 错误

### ISSUE THREAD

**Issue by wesleyxiao** [cong5/myPersimmon#23]
跟着教程走安装完后，进入后台或前台会出现The only supported ciphers are AES-128-CBC and AES-256-CBC 错误

然后需要输入 php artisan key:generate

才把错误解决掉

大神是不是要在教程前面提示一下 像我这样的初学者 比较容易一些 😁

**Comment by cong5** [comment]
感谢，这个我晚点更新上去。
