### ISSUE TITLE
你好，安装的时候报错了

### ISSUE THREAD

**Issue by ghost** [cong5/myPersimmon#27]
你好，我按照你的教程搭建，执行composer install的时候报错。我截取了一段代码麻烦您看一下：
 Installing phpunit/php-code-coverage (4.0.8): Downloading (failed)       
Downloading (failed)       
Downloading (failed)    Failed to download phpunit/php-code-coverage from dist: The "https://files.phpcomposer.com/files/sebastianbergmann/php-code-coverage/ef7b2f56815df854e66ceaee8ebe9393ae36a40d.zip" file could not be downloaded: failed to open stream: Connection refused
    Now trying to download from source
我尝试更新composer，也没有用

**Comment by hxsen** [comment]
你把composer.json里面的repositories，键值对删掉，然后把composer.lock这个文件删掉，然后再composer install试下
