### ISSUE TITLE
数据库获取之后user表是空的

### ISSUE THREAD

**Issue by terry-ice** [cong5/myPersimmon#5]
![22](https://cloud.githubusercontent.com/assets/18209670/25381126/30359b16-29e5-11e7-8cc8-2fb952b796bb.png)
![qq 20170425182827](https://cloud.githubusercontent.com/assets/18209670/25381130/32352c42-29e5-11e7-84a1-60bbdb20efe7.png)

**Comment by cong5** [comment]
用户的UsersTableSeeder没有执行，你在手动执行试试
```bash
php artisan db:seed --class=UsersTableSeeder
```
也可以在artisan模式下自己新建用户。
或者拉取最新的提交。最新的提交已经修复这个问题。

**Comment by terry-ice** [comment]
你什么时候提交的 ，我昨天晚上 mac 和windows 都是空的

**Comment by terry-ice** [comment]
刚我运行了，可以了 数据库有数据了

**Comment by cong5** [comment]
刚刚提交的。
本身用户数据的seeder是存在的，只是默认情况下不会自动填充，当你执行了 `php artisan db:seed --class=UsersTableSeeder` 的时候会填充用户数据了的。

**Comment by terry-ice** [comment]
ok 谢谢了 我要好好学习下，你的代码喽

**Comment by cong5** [comment]
哈哈，不用客气。如果在使用过程中有什么问题或者建议欢迎提Issue
