### ISSUE TITLE
请教一个小问题，如何指定 markdown 中代码的语言呢？

### ISSUE THREAD

**Issue by smartymoon** [cong5/myPersimmon#7]
![_20170506131951](https://cloud.githubusercontent.com/assets/12489528/25770078/bef15cce-325e-11e7-86c1-98fd4c45f936.png)
我尝试过使用 

![_20170506132145](https://cloud.githubusercontent.com/assets/12489528/25770093/1cf7bce6-325f-11e7-91ad-9dda4eaec5eb.png)

但并不生效

**Comment by cong5** [comment]
哦，我使用的代码高亮插件是[PrismJS](http://prismjs.com/)，代码高亮中的语言你看这里 [prismjs languages-list](http://prismjs.com/#languages-list)，如html代码，那么则是markup

**Comment by smartymoon** [comment]
thank you
