### ISSUE TITLE
分类下无文章报错

### ISSUE THREAD

**Issue by lostinfo** [cong5/myPersimmon#8]

**Comment by cong5** [comment]
@lostinfo 感谢你的反馈。你可以把报错信息贴出来么？

**Comment by lostinfo** [comment]
URL:http://www.localhost.com/category/mysql
FatalErrorException in HomeController.php line 69:
Call to a member function posts() on null

**Comment by cong5** [comment]
@lostinfo 嗯，好的。感谢。我知道是什么问题了。
